export const SETTING_DESCRIPTIONS: Record<string, string> = {
  'version': '현재 플러그인 버전',
  'plugin_name': '플러그인 이름',
  'dashboard_auth': '대시보드 인증 사용 여부',
  'branding.name': '브랜딩 이름',
  'branding.tagline': '브랜딩 태그라인',
  'workflow.max_feedback_rounds': '최대 피드백 반복 횟수 (Phase 4)',
  'workflow.auto_approve_spec': '스펙 자동 승인 여부',
  'workflow.auto_accept_result': 'Phase 3 리뷰 PASS 후 자동 수락',
  'workflow.default_agent': '기본 실행 에이전트',
  'server.port': '대시보드 포트',
  'server.host': '대시보드 호스트',
  'server.auth_enabled': '대시보드 Bearer 토큰 인증',
  'concurrency.max_parallel_tasks': '최대 병렬 태스크 수',
  'concurrency.max_parallel_reviews': '최대 병렬 리뷰 수',
  'concurrency.batch_max_parallel_reqs': '배치 승인 시 최대 병렬 REQ 수',
  'concurrency.queue_strategy': '큐 전략',
  'timeouts.cli_default_ms': 'CLI 기본 타임아웃 (5분)',
  'timeouts.cli_large_task_ms': '대규모 태스크 타임아웃 (30분)',
  'timeouts.pre_check_ms': '사전 검증 타임아웃 (2분)',
  'timeouts.merge_ms': 'Merge 타임아웃 (1분)',
  'timeouts.user_approval_ms': '사용자 승인 대기 타임아웃',
  'timeouts.dashboard_health_check_ms': '대시보드 헬스체크 (10초)',
  'worktree.root_directory': 'worktree 루트 경로',
  'worktree.max_active': '최대 활성 worktree 수',
  'worktree.base_branch': 'worktree 기준 브랜치',
  'worktree.stale_timeout_hours': 'stale 판정 시간',
  'worktree.auto_cleanup_on_cancel': '취소 시 자동 정리',
  'retry.max_cli_retries': 'CLI 최대 재시도 횟수',
  'retry.max_fallback_depth': '최대 fallback 깊이',
  'retry.backoff_base_ms': '재시도 백오프 기준 (ms)',
  'history.retention_days': '이력 보존 기간 (일)',
  'history.auto_archive': '자동 아카이브',
  'archive.max_active_sessions': '최대 활성 세션 수',
  'archive.archive_retention_days': '아카이브 보존 기간 (null=무기한)',
  'archive.auto_archive_on_create': '세션 생성 시 초과분 자동 아카이브',
  'archive.auto_archive_on_complete': '완료 시 자동 아카이브',
  'archive.archive_directory': '아카이브 저장 경로',
  'notifications.terminal': '터미널 알림',
  'notifications.dashboard': '대시보드 알림',
  'realtime.protocol': '실시간 프로토콜 (SSE)',
  'realtime.debounce_ms': '이벤트 디바운스 (ms)',
  'debug.enabled': '디버그 모드',
  'debug.log_level': '로그 레벨',
  'debug.log_prompts': '프롬프트 로깅',
  'discussion.response_char_limit': 'Discussion 응답 글자 제한',
  'discussion.critique_char_limit': 'Discussion Critic 글자 제한',
  'discussion.default_max_rounds': '기본 최대 라운드 수',
  'discussion.max_rounds_upper_limit': '최대 라운드 상한',
  'discussion.agents.codex': 'Discussion Codex 참여자 수',
  'discussion.agents.gemini': 'Discussion Gemini 참여자 수',
  'discussion.agents.claude': 'Discussion Claude 참여자 수',
  'ideation.opinion_char_limit': 'Ideation 의견 글자 제한',
  'ideation.critique_char_limit': 'Ideation Critic 글자 제한',
  'ideation.agents.codex': 'Ideation Codex 참여자 수',
  'ideation.agents.gemini': 'Ideation Gemini 참여자 수',
  'ideation.agents.claude': 'Ideation Claude 참여자 수',
  'collaborative_debug.finding_char_limit': '조사 결과 글자 제한',
  'collaborative_debug.merge_wait_ms': '에이전트 합류 대기 시간 (60초)',
  'collaborative_debug.auto_trigger_from_start': '/mst:start에서 디버그 의도 시 자동 트리거',
  'debug.agents.codex': 'Debug 조사 Codex 에이전트 수 (0=제외)',
  'debug.agents.gemini': 'Debug 조사 Gemini 에이전트 수 (0=제외)',
  'debug.agents.claude': 'Debug 조사 Claude 에이전트 수 (0=제외)',
  'models.claude.pm_conductor': 'PM 지휘자 (Phase 1, 3)',
  'models.claude.architect': '아키텍트 (Design Wing)',
  'models.claude.ideation': 'Ideation 참여자',
  'models.claude.discussion': 'Discussion 참여자',
  'models.claude.debug': 'Debug 참여자',
  'models.gemini.default': 'Gemini 기본 모델',
  'models.developer.primary.provider': '주 개발자 provider',
  'models.developer.primary.model': '주 개발자 모델명',
  'models.developer.fallback.provider': '보조 개발자 provider',
  'models.developer.fallback.model': '보조 개발자 모델명',
  'models.developer.claude_dev.provider': 'Claude 개발자 provider',
  'models.developer.claude_dev.model': 'Claude 개발자 모델명',
  'models.reviewer.primary.provider': '주 리뷰어 provider',
  'models.reviewer.primary.model': '주 리뷰어 모델명',
  'models.reviewer.fallback.provider': '보조 리뷰어 provider',
  'models.reviewer.fallback.model': '보조 리뷰어 모델명',
  'code_review.enabled': '코드 리뷰 활성화',
  'code_review.agents': '코드 리뷰 참여 에이전트 수',
  'code_review.agent_roster': '코드 리뷰 에이전트 명단',
  'code_review.parallel': '병렬 코드 리뷰',
  'cleanup.ideation_keep_count': 'Ideation 세션 유지 수',
  'cleanup.discussion_keep_count': 'Discussion 세션 유지 수',
  'cleanup.debug_keep_count': 'Debug 세션 유지 수',
  'cleanup.old_request_threshold_hours': '오래된 요청 판단 기준 (시간)',
  'stitch.enabled': 'Stitch UI 설계 기능 활성화',
  'stitch.auto_detect': 'UI 변경 자동 감지',
  'stitch.auto_trigger': '자동 Stitch 실행',
  'stitch.project_id': 'Stitch 프로젝트 ID',
  'stitch.failure_policy': 'Stitch 실패 정책',
};
